/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BD_Registros;
import controller.Filtro;
import controller.csv.CSVGerador;
import java.awt.Color;
import java.io.File;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JToggleButton;
import javax.swing.filechooser.FileFilter;
import model.registros.Registro;
import model.registros.RegistroTableModel;
import model.usuario.UsuarioAdmin;
import model.usuario.UsuarioComum;

/**
 *
 * @author Gabriel
 */
public class Main extends javax.swing.JFrame {
    
    private UsuarioComum usuario = null;
    private UsuarioAdmin admin = null;
    
    private BD_Registros bd = new BD_Registros();
    private ArrayList<Registro> registrosUsuarioInicial = new ArrayList<>();
    private RegistroTableModel tableModel = new RegistroTableModel();
    private Filtro filtro = new Filtro();
    
    
    public Main(UsuarioComum usuario) {
        this.usuario = usuario;
        this.registrosUsuarioInicial = bd.getRegistrosUsuario(usuario.getId());
        
        initComponents();
        
        this.labelNome.setText(this.usuario.getPessoa().getNome());
        
        jTable1.setModel(tableModel);
        tableModel.iniciarDados(usuario.getId());
        
        this.refreshTotal();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public Main(UsuarioAdmin admin) {
        this.admin = admin;
        
        initComponents();
        
        jTable1.setModel(tableModel);
        this.labelNome.setText("Administrador");
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        verificarDados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        novoRegistro = new javax.swing.JButton();
        jPanelTotal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        alterarRegistro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        filtrarTipo = new javax.swing.JToggleButton();
        jComboBoxForma = new javax.swing.JComboBox<>();
        filtrarForma = new javax.swing.JToggleButton();
        jComboBoxCondicao = new javax.swing.JComboBox<>();
        filtrarCondicoes = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDataOperacaoFinal = new javax.swing.JTextField();
        filtrarDataOperacao = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDataOperacao = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filtrarValor = new javax.swing.JToggleButton();
        jTextFieldValorMax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValorMin = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        filtrarDescricao = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldResponsavel = new javax.swing.JTextField();
        filtrarResponsavel = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDataVencimentoFinal = new javax.swing.JTextField();
        jTextFieldDataVencimento = new javax.swing.JTextField();
        filtrarDataVencimento = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        gerarCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 91, 73));

        jPanel2.setBackground(new java.awt.Color(24, 135, 82));
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        labelNome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelNome.setForeground(new java.awt.Color(250, 250, 250));
        labelNome.setText("Nome");

        sair.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        verificarDados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        verificarDados.setText("Verificar Meus Dados");
        verificarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verificarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verificarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        novoRegistro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        novoRegistro.setText("Novo Registro");
        novoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoRegistroActionPerformed(evt);
            }
        });

        jPanelTotal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Total");

        total.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        total.setForeground(new java.awt.Color(153, 153, 153));
        total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total.setText("100000.00");

        javax.swing.GroupLayout jPanelTotalLayout = new javax.swing.GroupLayout(jPanelTotal);
        jPanelTotal.setLayout(jPanelTotalLayout);
        jPanelTotalLayout.setHorizontalGroup(
            jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTotalLayout.setVerticalGroup(
            jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        alterarRegistro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        alterarRegistro.setText("Alterar Registro");
        alterarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarRegistroActionPerformed(evt);
            }
        });

        jComboBoxTipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudo", "Rancho", "Higiene", "Conveniência", "Lazer", "Lucro", "Saúde", "Casa", "Manutenção", "Rendimento" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });

        filtrarTipo.setText("Filtrar");
        filtrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarTipoActionPerformed(evt);
            }
        });

        jComboBoxForma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de Crédito", "Cartão de Débito", "Cheque", "Dinheiro", "Transferência Bancária" }));
        jComboBoxForma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFormaItemStateChanged(evt);
            }
        });

        filtrarForma.setText("Filtrar");
        filtrarForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarFormaActionPerformed(evt);
            }
        });

        jComboBoxCondicao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxCondicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "À Prazo", "À Vista" }));
        jComboBoxCondicao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCondicaoItemStateChanged(evt);
            }
        });

        filtrarCondicoes.setText("Filtrar");
        filtrarCondicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarCondicoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(filtrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filtrarForma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxCondicao, 0, 128, Short.MAX_VALUE)
                    .addComponent(filtrarCondicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrarCondicoes)
                    .addComponent(filtrarForma)
                    .addComponent(filtrarTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Data");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Data Final");

        jTextFieldDataOperacaoFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDataOperacaoFinal.setText("dd/mm/aaaa");
        jTextFieldDataOperacaoFinal.setToolTipText("Data Final (DD/MM/AAAA)");

        filtrarDataOperacao.setText("Filtrar");
        filtrarDataOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDataOperacaoActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data Operação");

        jTextFieldDataOperacao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDataOperacao.setText("dd/mm/aaaa");
        jTextFieldDataOperacao.setToolTipText("Data Final (DD/MM/AAAA)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDataOperacao)
                            .addComponent(jTextFieldDataOperacaoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrarDataOperacao)
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDataOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataOperacaoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(filtrarDataOperacao)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor Máx");

        filtrarValor.setText("Filtrar");
        filtrarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarValorActionPerformed(evt);
            }
        });

        jTextFieldValorMax.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Valor Min");

        jTextFieldValorMin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldValorMin, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jTextFieldValorMax)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(filtrarValor)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldValorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrarValor)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Descrição");

        jTextFieldDescricao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        filtrarDescricao.setText("Filtrar");
        filtrarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filtrarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrarDescricao)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Responsável");

        jTextFieldResponsavel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        filtrarResponsavel.setText("Filtrar");
        filtrarResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarResponsavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(filtrarResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrarResponsavel)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Data");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Data Final");

        jTextFieldDataVencimentoFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDataVencimentoFinal.setText("dd/mm/aaaa");
        jTextFieldDataVencimentoFinal.setToolTipText("Data Final (DD/MM/AAAA)");

        jTextFieldDataVencimento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDataVencimento.setText("dd/mm/aaaa");
        jTextFieldDataVencimento.setToolTipText("Data Inicial (DD/MM/AAAA)");

        filtrarDataVencimento.setText("Filtrar");
        filtrarDataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDataVencimentoActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DataVencimento");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrarDataVencimento)
                .addGap(82, 82, 82))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDataVencimentoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataVencimentoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtrarDataVencimento)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        gerarCSV.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        gerarCSV.setText("Gerar CSV");
        gerarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(novoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alterarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gerarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alterarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private ArrayList<String> getDadosFiltro(){
        ArrayList<String> a = new ArrayList<>();
        
        a.add(this.jTextFieldResponsavel.getText()); //0
        a.add(this.jTextFieldDescricao.getText()); //1
        a.add(this.jTextFieldValorMax.getText()); //2
        a.add(this.jTextFieldValorMin.getText()); //3
        
        a.add(this.jTextFieldDataVencimento.getText()); //4
        a.add(this.jTextFieldDataVencimentoFinal.getText()); //5
        
        a.add(this.jTextFieldDataOperacao.getText()); //6
        a.add(this.jTextFieldDataOperacaoFinal.getText()); //7
        
        a.add(this.jComboBoxTipo.getSelectedItem().toString()); //8
        a.add(this.jComboBoxForma.getSelectedItem().toString()); //9
        a.add(this.jComboBoxCondicao.getSelectedItem().toString()); //10
                
        return(a);
    }
    
    private ArrayList<JToggleButton> getEstadoFiltro(){
        ArrayList<JToggleButton> a = new ArrayList<>();
        
        a.add(this.filtrarResponsavel); //0
        a.add(this.filtrarDescricao); //1
        a.add(this.filtrarValor); //2
        a.add(this.filtrarDataVencimento); //3
        a.add(this.filtrarDataOperacao); //4
        a.add(this.filtrarTipo); //5
        a.add(this.filtrarForma); //6
        a.add(this.filtrarCondicoes); //7
        
        return(a);
    }
    
    private void refreshTotal(){
        this.setColorTotal(Double.parseDouble(this.getTotal()));
        this.total.setText(this.getTotal());
    }
    
    private void setColorTotal(double valor){
        if(valor > 0){
            this.total.setForeground(Color.GREEN);
        }else{
            this.total.setForeground(Color.RED);
        }
    }
    
    private String getTotal(){
        DecimalFormat formatador = new DecimalFormat("0.00");
        int i=0;
        double soma=0;
        
        while(i < this.tableModel.getRowCount()){
            soma = soma + Double.parseDouble(this.tableModel.getValueAt(i, 2).toString());
            i++;
        }
        
        return("" + formatador.format(soma));
    }
    
    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        this.dispose();
        new Login();
    }//GEN-LAST:event_sairActionPerformed

    private void verificarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarDadosActionPerformed
        this.dispose();
        new DadosUsuario(this.usuario);
    }//GEN-LAST:event_verificarDadosActionPerformed

    private void novoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoRegistroActionPerformed
        this.dispose();
        new NovoRegistro(this.usuario);
    }//GEN-LAST:event_novoRegistroActionPerformed

    private void alterarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarRegistroActionPerformed
        this.dispose();
        new InsertNumber(usuario);
    }//GEN-LAST:event_alterarRegistroActionPerformed

    private void filtrarResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarResponsavelActionPerformed
        if(!(this.jTextFieldResponsavel.getText().equals("")) && this.filtrarResponsavel.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarResponsavelActionPerformed

    private void filtrarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDescricaoActionPerformed
        if(!(this.jTextFieldDescricao.getText().equals("")) && this.filtrarDescricao.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarDescricaoActionPerformed

    private void filtrarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarValorActionPerformed
        if(!(this.jTextFieldValorMax.getText().equals("")) && !(this.jTextFieldValorMin.getText().equals("")) && this.filtrarValor.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarValorActionPerformed

    private void filtrarDataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDataVencimentoActionPerformed
        if(!(this.jTextFieldDataVencimento.getText().equals("")) && !(this.jTextFieldDataVencimentoFinal.getText().equals("")) && this.filtrarDataVencimento.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarDataVencimentoActionPerformed

    private void filtrarDataOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDataOperacaoActionPerformed
        if(!(this.jTextFieldDataOperacao.getText().equals("")) && !(this.jTextFieldDataOperacaoFinal.getText().equals("")) && this.filtrarDataOperacao.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarDataOperacaoActionPerformed

    private void filtrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarTipoActionPerformed
        if(this.filtrarTipo.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarTipoActionPerformed

    private void filtrarFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarFormaActionPerformed
        if(this.filtrarForma.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarFormaActionPerformed

    private void filtrarCondicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarCondicoesActionPerformed
        if(this.filtrarCondicoes.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }else{
            this.tableModel.setData(this.registrosUsuarioInicial);
            this.refreshTotal();
            
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_filtrarCondicoesActionPerformed

    private void gerarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarCSVActionPerformed
        JFileChooser seletorPath = new JFileChooser();
        
        seletorPath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int i = seletorPath.showSaveDialog(null);
        if (i == 1){
           
        }else{
            CSVGerador geradorCSV = new CSVGerador();
            geradorCSV.gerarCsv(seletorPath.getSelectedFile().toString(), this.tableModel.getRegistrosMostrados());
            System.out.println(seletorPath.getSelectedFile().toString());
        }
    }//GEN-LAST:event_gerarCSVActionPerformed

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        if(this.filtrarTipo.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jComboBoxFormaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFormaItemStateChanged
        if(this.filtrarForma.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_jComboBoxFormaItemStateChanged

    private void jComboBoxCondicaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCondicaoItemStateChanged
        if(this.filtrarCondicoes.isSelected()){
            ArrayList<String> dadosFiltro;
            ArrayList<JToggleButton> estadosFiltro;

            dadosFiltro = this.getDadosFiltro();
            estadosFiltro = this.getEstadoFiltro();

            this.tableModel.setData(this.filtro.filtrar(dadosFiltro, estadosFiltro, this.registrosUsuarioInicial));
            this.refreshTotal();
        }
    }//GEN-LAST:event_jComboBoxCondicaoItemStateChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarRegistro;
    private javax.swing.JToggleButton filtrarCondicoes;
    private javax.swing.JToggleButton filtrarDataOperacao;
    private javax.swing.JToggleButton filtrarDataVencimento;
    private javax.swing.JToggleButton filtrarDescricao;
    private javax.swing.JToggleButton filtrarForma;
    private javax.swing.JToggleButton filtrarResponsavel;
    private javax.swing.JToggleButton filtrarTipo;
    private javax.swing.JToggleButton filtrarValor;
    private javax.swing.JButton gerarCSV;
    private javax.swing.JComboBox<String> jComboBoxCondicao;
    private javax.swing.JComboBox<String> jComboBoxForma;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDataOperacao;
    private javax.swing.JTextField jTextFieldDataOperacaoFinal;
    private javax.swing.JTextField jTextFieldDataVencimento;
    private javax.swing.JTextField jTextFieldDataVencimentoFinal;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JTextField jTextFieldValorMax;
    private javax.swing.JTextField jTextFieldValorMin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JButton novoRegistro;
    private javax.swing.JButton sair;
    private javax.swing.JLabel total;
    private javax.swing.JButton verificarDados;
    // End of variables declaration//GEN-END:variables
}
